version: 2.0
jobs:
  build:
    docker:
      - image: ruby:2.3
    working_directory: ~/danger-linear_history
    steps:
      - checkout
      - restore_cache:
          key: << checksum "Gemfile.lock" >>
      - run: bundle check --path=.bundle || bundle install --path=.bundle --jobs=4 --retry=3
      - cache-save:
          key: << checksum "Gemfile.lock" >>
          paths:
            - ~/danger-linear_history/.bundle
      - run: bundle exec rake spec
